/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResumeImport } from './routes/resume'
import { Route as ProjectsImport } from './routes/projects'
import { Route as CoursesImport } from './routes/courses'
import { Route as CertificationsImport } from './routes/certifications'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ResumeRoute = ResumeImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsRoute = ProjectsImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any)

const CoursesRoute = CoursesImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRoute,
} as any)

const CertificationsRoute = CertificationsImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsImport
      parentRoute: typeof rootRoute
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsImport
      parentRoute: typeof rootRoute
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certifications': typeof CertificationsRoute
  '/courses': typeof CoursesRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certifications': typeof CertificationsRoute
  '/courses': typeof CoursesRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/certifications': typeof CertificationsRoute
  '/courses': typeof CoursesRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/certifications' | '/courses' | '/projects' | '/resume'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/certifications' | '/courses' | '/projects' | '/resume'
  id:
    | '__root__'
    | '/'
    | '/certifications'
    | '/courses'
    | '/projects'
    | '/resume'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificationsRoute: typeof CertificationsRoute
  CoursesRoute: typeof CoursesRoute
  ProjectsRoute: typeof ProjectsRoute
  ResumeRoute: typeof ResumeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificationsRoute: CertificationsRoute,
  CoursesRoute: CoursesRoute,
  ProjectsRoute: ProjectsRoute,
  ResumeRoute: ResumeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/certifications",
        "/courses",
        "/projects",
        "/resume"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/certifications": {
      "filePath": "certifications.tsx"
    },
    "/courses": {
      "filePath": "courses.tsx"
    },
    "/projects": {
      "filePath": "projects.tsx"
    },
    "/resume": {
      "filePath": "resume.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
